Repository shikorism/tissue, pull requests merged in 2020-06, with the labels that each got.

#368 dependabotのセットアップ
  .github/dependabot.yml
Labels: enhancement

#382 Release 20200603.2340
  .circleci/config.yml
  .github/dependabot.yml
  app/Providers/AppServiceProvider.php
  composer.lock
  package.json
  yarn.lock
Labels: release

#396 [fix] lint-staged のglobパターンが誤ってた
  package.json
Labels: bug
